app = 'tunix-crm-backend'
primary_region = 'dfw'

[env]
  NODE_ENV = "production"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 3000  
  protocol = "tcp"

  [[services.ports]]
    port = "80"
    handlers = ["http"]

  [[services.ports]]
    port = "443"
    handlers = ["tls", "http"]