name: Fly Deploy
on:
  push:
    branches:
      - main # change to main if needed
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # makes flyctl auth happen automatically
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        # optionally pin to a version:
        # with:
        #   version: v0.0.400       # or “latest”

      - name: Deploy to Fly
        run: flyctl deploy --config fly.toml --app hello-world-nest
